#!/bin/env php
<?php
	
	class Query {
		var $n;
		var $root;
		var $qf;
		var $input;
		var $output;
		var $SELECT;
		var $LIMIT;
		var $FROM = array();
		var $NOT;
		var $LEFT;
		var $OPERATOR;
		var $RIGHT;	
	}

	function getAction($xqr, $argc, $argv, $stderr) {
		$arguments = $argv;
		foreach ($argv as $value) {
			unset($argv[0]);

			//--help
			if(preg_match("/--help/", $value)) {
				printHelp();
				exit (0);
			}
			//-n
			if(preg_match("/-n/", $value)) {
				$xqr->n = TRUE;
				unset($argv[array_search($value, $argv)]);
			}
			//--root
			if(preg_match("/--root=/", $value))  {
				if(preg_match('/\A(?!XML)[a-z][\w0-9-]*/i', substr($value, 7))) {
					$xqr->root = TRUE;
					unset($argv[array_search($value, $argv)]);
				} else {
					fwrite($stderr, "Error: ROOT neni platny element\n");
					exit (1);
				}
			}
			//--qf
			if(preg_match("/--qf=.+/", $value)) {
				if(isset($xqr->input)) {
					fwrite($stderr, "Error: kombinace --query & --qf\n");
					exit (1);
				}
				$xqr->qf = substr($value, 5);
				unset($argv[array_search($value, $argv)]);

				if(! file_exists($xqr->qf)) {
					fwrite($stderr, "Error: soubor $xqr->qf neexistuje\n");
					exit (1);
				}
				if(($qf = fopen($xqr->qf, 'r')) === FALSE){
					fwrite($stderr, "Error: nepodarilo se otevrit soubor $xqr->qf\n");
					exit (1); //TODO: error code
				}

			}
			//--input
			if(preg_match("/--input=.+/", $value)) {
				$xqr->input = substr($value, 8);
				unset($argv[array_search($value, $argv)]);
			}
			//--output
			if(preg_match("/--output=.+/", $value)) {
				$xqr->output = substr($value, 9);
				unset($argv[array_search($value, $argv)]);
			}


		}

		foreach ($argv as $value) {
			fwrite($stderr, "Error: neplatne argumenty\n");
			fwrite($stderr, "Run $arguments[0] --help instead\n");
			exit (1);
		}
	}

	function getOpts($argc, $argv) {
		$result = '';
		for ($i=1; $i < $argc; $i++)
			if($i != $argc -1)
				$result .= $argv[$i].' ';
			else 
				$result .= $argv[$i];
		//--help
		if(preg_match('/'.'--help'.'/', $result)) {
			printHelp();
			exit (0);
		}
		//--output
		$temp = array();
		if(preg_match("/--output=(.*?)(?:\s+--|$)/", $result, $temp)) {
			print_r($temp);
		}		//--input
		if(preg_match("/--input=(.*?)(?:\s+--|$)/", $result, $temp))
			print_r($temp);
		preg_replace('/--input=input s mezerou.xml/', '', $result);
		var_dump($result);
	}


	function printHelp() {
		printf("Obsah napovedy\n");
	}

	$stderr = fopen('php://stderr', 'a');

	$xqr = new Query;

	getAction($xqr, $argc, $argv, $stderr);
	// var_dump($xqr);
	

?>